#!/bin/sh

protected_branch='master'

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $current_branch = $protected_branch ]]; then
    echo "Pushing new config to Heroku."
    heroku config:add METEOR_SETTINGS="$(cat private/config.json)"
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
        echo "Not pushing since failed pushing config to Heroku."
        exit 1
    fi
fi
exit 0
